### ISSUE TITLE
ArrayIndexOutOfBoundsException for Ctrl+Shift+G find references

### ISSUE THREAD

**Issue by garretwilson** [eclipse-jdt/eclipse.jdt.core#115]
First of all congratulations for moving to a modern bug reporting system! 🎉 If this is the wrong subproject to report this bug, please direct me to the right one.

eclipse.buildId=4.23.0.I20220308-0310
java.version=17.0.2
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

I recently upgraded to Eclipse 4.23 on Windows 10 by unzipping `eclipse-jee-2022-03-R-win32-x86_64.zip` and using my existing workspace which I've been using for literally decades with Eclipse. I immediately ran into all sorts of odd bugs, especially with Maven-related things.

But here's a bug that appeared when I just pressed `Ctrl+Shift+G` to find references to a class. Here is the error with stack trace:

> An internal error occurred during: "Java Search".

```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.eclipse.jdt.internal.compiler.ast.QualifiedTypeReference.getTypeBinding(QualifiedTypeReference.java:133)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:522)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:634)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:630)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveSuperType(TypeReference.java:602)
	at org.eclipse.jdt.internal.compiler.lookup.ClassScope.findSupertype(ClassScope.java:1670)
	at org.eclipse.jdt.internal.compiler.lookup.ClassScope.connectSuperclass(ClassScope.java:1176)
	at org.eclipse.jdt.internal.compiler.lookup.ClassScope.connectTypeHierarchy(ClassScope.java:1454)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.connectTypeHierarchy(CompilationUnitScope.java:367)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:586)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.accept(MatchLocator.java:381)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:334)
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:276)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getTypeOrPackage(Scope.java:3466)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:3173)
	at org.eclipse.jdt.internal.compiler.ast.SingleTypeReference.getTypeBinding(SingleTypeReference.java:57)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:522)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:625)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:621)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesWithSuspendedTempErrorHandlingPolicy(SourceTypeBinding.java:2870)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypesFor(SourceTypeBinding.java:2705)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.methods(SourceTypeBinding.java:2276)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.internalFaultInTypeForFieldsAndMethods(SourceTypeBinding.java:1518)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.faultInTypesForFieldsAndMethods(SourceTypeBinding.java:1113)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:533)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2021)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1353)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1390)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1509)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:251)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:602)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:670)
	at org.eclipse.jdt.internal.ui.search.JavaSearchQuery.run(JavaSearchQuery.java:178)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:94)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I likely cannot provide further details for reproducing this bug; hopefully the stack track will give you an idea of what went wrong.

(This was originally filed as https://github.com/eclipse-platform/eclipse.platform/issues/24 .)

**Comment by iloveeclipse** [comment]
> eclipse.buildId=4.23.0.I20220308-0310

Would you please try 4.24 RC1?  https://download.eclipse.org/eclipse/downloads/drops4/S-4.24RC1-202205251800/

**Comment by garretwilson** [comment]
I apologize but at the moment I don't have the extra time to install release candidates and try this out. (Do you know if a particular change was made that should fix this, or are you just wanting to try different things in case we got lucky and it doesn't happen anymore?) I did want to file the ticket so that you'll be aware of the problem. Once 2022-06 is released I'll certainly update the ticket if it happens again.

**Comment by iloveeclipse** [comment]
I just see that the stack trace doesn't match master code, so it would be easier to get the most recent stack in case the problem is still not solved. And yes, between two releases many things could have changed, like merge of Java 18 support branch etc.

**Comment by garretwilson** [comment]
That makes sense. OK, I look forward to seeing if this is fixed in the final release of 2022-06. Thanks.

**Comment by garretwilson** [comment]
Funny, a similar error with a similar stack trace is now showing up in 2022-06 in issue #154, but from a different sequence of user events. Looks like there is some nasty internal bug with type resolution/binding that is causing errors across functionality.

**Comment by garretwilson** [comment]
This bug is appearing again in Eclipse EE 2022-06, and it's closely associated with issue #154. In fact it shows up when I try to search for references of the class I'm trying to rename in issue #154. I would bet this stems from the same bug. This is really getting in the way of development.

```
eclipse.buildId=4.24.0.I20220607-0700
java.version=17.0.3
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

org.eclipse.core.jobs
Error
Tue Jul 05 07:44:59 PDT 2022
An internal error occurred during: "Java Search".

java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.eclipse.jdt.internal.compiler.ast.QualifiedTypeReference.getTypeBinding(QualifiedTypeReference.java:133)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:522)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:634)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:630)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveSuperType(TypeReference.java:602)
	at org.eclipse.jdt.internal.compiler.lookup.ClassScope.findSupertype(ClassScope.java:1670)
	at org.eclipse.jdt.internal.compiler.lookup.ClassScope.connectSuperclass(ClassScope.java:1176)
	at org.eclipse.jdt.internal.compiler.lookup.ClassScope.connectTypeHierarchy(ClassScope.java:1454)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.connectTypeHierarchy(CompilationUnitScope.java:367)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(LookupEnvironment.java:586)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.accept(MatchLocator.java:381)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.askForType(LookupEnvironment.java:334)
	at org.eclipse.jdt.internal.compiler.lookup.PackageBinding.getTypeOrPackage(PackageBinding.java:276)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getTypeOrPackage(Scope.java:3466)
	at org.eclipse.jdt.internal.compiler.lookup.Scope.getType(Scope.java:3173)
	at org.eclipse.jdt.internal.compiler.ast.SingleTypeReference.getTypeBinding(SingleTypeReference.java:57)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.internalResolveType(TypeReference.java:522)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:625)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveTypeArgument(TypeReference.java:638)
	at org.eclipse.jdt.internal.compiler.ast.ParameterizedSingleTypeReference.internalResolveLeafType(ParameterizedSingleTypeReference.java:264)
	at org.eclipse.jdt.internal.compiler.ast.ParameterizedSingleTypeReference.internalResolveType(ParameterizedSingleTypeReference.java:174)
	at org.eclipse.jdt.internal.compiler.ast.ParameterizedSingleTypeReference.resolveType(ParameterizedSingleTypeReference.java:390)
	at org.eclipse.jdt.internal.compiler.ast.TypeReference.resolveType(TypeReference.java:621)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.resolveTypeFor(SourceTypeBinding.java:2627)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.fields(SourceTypeBinding.java:1550)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.internalFaultInTypeForFieldsAndMethods(SourceTypeBinding.java:1517)
	at org.eclipse.jdt.internal.compiler.lookup.SourceTypeBinding.faultInTypesForFieldsAndMethods(SourceTypeBinding.java:1113)
	at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.faultInTypes(CompilationUnitScope.java:533)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.process(MatchLocator.java:2021)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1353)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1390)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.locateMatches(MatchLocator.java:1509)
	at org.eclipse.jdt.internal.core.search.JavaSearchParticipant.locateMatches(JavaSearchParticipant.java:135)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.findMatches(BasicSearchEngine.java:251)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.search(BasicSearchEngine.java:602)
	at org.eclipse.jdt.core.search.SearchEngine.search(SearchEngine.java:670)
	at org.eclipse.jdt.internal.ui.search.JavaSearchQuery.run(JavaSearchQuery.java:178)
	at org.eclipse.search2.internal.ui.InternalSearchUI$InternalSearchJob.run(InternalSearchUI.java:94)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by garretwilson** [comment]
Oh, no, this just happened again, now with a very well-established library (decades!) I have been maintaining, [globalmentor-base](https://github.com/globalmentor/globalmentor-base). Specifically I am on commit 038d51609ee4ad620a245e9b450f056ea78cbb12 (though I hardly expect the specific commit matters). In `com.globalmentor.security.MessageDigests.Algorithm` I did a `Ctrl+G` search for all the references to `com.globalmentor.security.MessageDigests.Algorithm.getInstance()`. I got the `ArrayIndexOutOfBoundsException`.

But here is something interesting: remember in #154 that I said that when I closed a new project `example-project` which was referring to the class I was refactoring, I was able to refactor? I tried the same thing here: I closed `example-project` (which referred to `com.globalmentor.security.MessageDigests.Algorithm.getInstance()`), and suddenly I was able to search for occurrences of `MessageDigests.Algorithm.getInstance()` without the error! At this point it's clear:

* This issue #115 and #154 almost definitely have the same root cause.
* Something about the new project I'm working on, which references the classes I'm refactoring or searching for references of, is causing the issue to appear (whether or not it is actually causing the issue).

I tried actually removing `example-project` from the workspace and adding it back; unfortunately that didn't help.

I removed `example-project` again, but this time I deleted the `.settings` and `target` directories, as well as the `.project`, and `.classpath` files. Then I reimported `example-project`. Still the problem persisted.

The project `example-project` is a Maven project, and its parent POM (it has two subprojects) uses [globalmentor-root](https://github.com/globalmentor/globalmentor-root), currently at commit fb254dae4e01d561a4593fddd1d2a4ecb0f107a1, as its parent:

```
  <parent>
    <groupId>com.globalmentor</groupId>
    <artifactId>globalmentor-root</artifactId>
    <version>0.8.10-SNAPSHOT</version>
  </parent>
```

Then `example-project` has this in dependency management:

```
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.globalmentor</groupId>
        <artifactId>globalmentor-parent</artifactId>
        <version>8.6.0</version>
        <type>pom</type>
        <scope>import</scope>
        </dependency>

      <dependency>
        <groupId>com.globalmentor</groupId>
        <artifactId>globalmentor-core</artifactId>
        <version>0.7.1-SNAPSHOT</version>
      </dependency>
...
```

Note that `com.globalmentor:globalmentor-parent:8.6.0` pulls in an earlier version of `com.globalmentor:globalmentor-core`, which is why I override it to the `0.7.1-SNAPSHOT` snapshot.

So listen to this: when I remove the reference to `com.globalmentor:globalmentor-core:0.7.1-SNAPSHOT` (the version of `globalmentor-core` I have loaded in the project and which is causing refactoring errors, etc.), I can search for references to `MessageDigests.Algorithm.getInstance()` with no problem!

So the error has something to do with `example-project` referencing the `com.globalmentor:globalmentor-core:0.7.1-SNAPSHOT` project.

But I have other projects in the workspace that reference `com.globalmentor:globalmentor-core:0.7.1-SNAPSHOT` and even reference `MessageDigests.Algorithm.getInstance()`, and they don't cause the error to appear! However notes that `example-project` is the only project I have imported into the workspace after installing Eclipse EE 2022-03/2022-06.

I closed `example-project` and pulled out a tiny template Maven project and imported it into the workspace. I set its parent as `com.globalmentor:globalmentor-root:0.8.10-SNAPSHOT`, I added `com.globalmentor:globalmentor-parent:8.6.0` and `com.globalmentor:globalmentor-core:0.7.1-SNAPSHOT` to the dependency management section, and then added a dependency to `com.globalmentor:globalmentor-core`. In the code I added a reference to `MessageDigests.SHA3_256.getInstance()`. Then I tried to search for references to `com.globalmentor.security.MessageDigests.Algorithm.getInstance()`. Still no error.

Thus there is something about `example-project` that is causing the error to appear, and it only appears if `example-project` references the `globalmentor-core` I have opened in the workspace, although that condition isn't sufficient to cause the error as a separate test project with the same references doesn't cause the problem to show up.

**Comment by garretwilson** [comment]
Arg, this is happening again with a completely different method. I have the project [`globalmentor-base`](https://github.com/globalmentor/globalmentor-base/) open in the workspace. I have the class [`Character`](Characters) open, and I'm trying to search for references to `Characters.appendUnicodeString(final StringBuilder stringBuilder, final int c)`. I get this dreaded `ArrayIndexOutOfBoundsException`.

In this case, the `Characters.appendUnicodeString()` isn't referenced by `example-project`. In fact it's not even referenced anywhere outside of the `Characters` class!

This is frustrating that such a fundamental day-today functionality of Eclipse is so utterly broken.

**Comment by trancexpress** [comment]
Without anything to reproduce we can only guess what is causing the split package conflict and why there is a package with no name involved (maybe the default package?). No qualified name for the package leads to the `-1` index; from my POV adding a check for that index would be trying to deal with a symptom and not the actual problem.

I checked out https://github.com/globalmentor/globalmentor-base/ alone, no issue with only this project. Whatever is causing trouble must be in the `example-project` you have mentioned in several places.

> In this case, the `Characters.appendUnicodeString()` isn't referenced by `example-project`. In fact it's not even referenced anywhere outside of the `Characters` class!

The search for references will anyway go through `example-project` - it has to determine there are no such references.

> This is frustrating that such a fundamental day-today functionality of Eclipse is so utterly broken.

If this frustrates you enough I can give pointers how you can debug the problem, maybe that would yield useful information. You have an Eclipse SDK, so it should not be too much trouble.

**Comment by jukzi** [comment]
@garretwilson please contribute at least a minimal reproducer.
